### PR TITLE
Add SwingLeft.org

### PR DESCRIPTION
**Pull request by mikimer**

### CODE REVIEW

**Comment by katerabinowitz** [comment]
@mikimer love this! is there a data/tech component that coders can contribute to?

**Comment by mikimer** [comment]
I hope there'll be a specific tech component. SwingLeft has it's first organization call this Sunday, so I'm gonna be on the call and hope to ask then.

**Comment by katerabinowitz** [comment]
Cool! So as not to overwhelm people I want to limit the list to organizations that are specifically seeking programming assistance. So for now I'm going to close this pr but please do submit a new if there are more specific ways for the tech community to lean in. Thanks!

**Comment by mikimer** [comment]
sounds good. I reached out to Swing Left about tech help -- if they give me
something specific, I'll ping you

2017-02-13 16:09 GMT-08:00 Kate Rabinowitz <notifications@github.com>:

**Pull request closed without merging**
